import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Controle Finanças",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen">
          <div className="flex flex-1 overflow-hidden">
            <Navbar />
            <main className="flex-1 p-8 overflow-y-auto bg-gray-100">
              {children}
            </main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
